### ISSUE TITLE
Linux Support

### ISSUE THREAD

**Issue by LolTDMMMOs** [SexuallyAbusive/Zyklon#21]
Hey! I find your client fascinating and am trying to use it but am unable to. Does the client have Linux support?

**Comment by xertxa** [comment]
implementing linux support should be easy, probably the only thing you'd have to change would be path of the tools.jar file in the jdk. this is located and added to the classloader at runtime here:
https://github.com/xertxa/Zyklon/blob/master/injector/src/respectful/rapist/injector/Main.java#L21

**Comment by explodersname** [comment]
In doing this would I have to build it myself?

**Comment by explodersname** [comment]
Update: I've spent the past hour trying to get this to work on java myself and am yet to be successful. I may try again some other time but for now I'm taking a break

**Comment by explodersname** [comment]
Update: I have built the client but am not sure if it'll work. Hope it does.

**Comment by explodersname** [comment]
Just as I thought It didnt Work. I'll just leave it to xertxa to do it officially.

**Comment by 3Q6Dev** [comment]
I believe that this issue can be closed, since Zyklon now fully supports linux and mac.

**Comment by LolTDMMMOs** [comment]
Linux support has been fully added.
