### ISSUE TITLE
Minecraft Forge 1.7.10/1.8.9 does not get detected.

### ISSUE THREAD

**Issue by scarifyFX** [SexuallyAbusive/Zyklon#47]
I was trying to use the cheat but nothing was working, I was able to inject it but not use the cheat. I enabled them but they didn't work not even the hud.

**Comment by scarifyFX** [comment]
Update  i watched a video and found out it dosen't inject like the video.

**Comment by scarifyFX** [comment]
Update: When i set up java_home it was done not right. Forge 1.7.10 does not work stable version. 1.8.9 either, stable. 
![Skärmbild (37)](https://user-images.githubusercontent.com/47931007/102925699-30d44b80-4494-11eb-8b81-d73ec07ed3fa.png) -1.8.9 screenshot

**Comment by scarifyFX** [comment]
Update: tried doing this https://github.com/SexuallyAbusive/Zyklon/issues/9 that still gave me the same problem.

**Comment by scarifyFX** [comment]
Installed a much older does not work.

**Comment by scarifyFX** [comment]
installed 3.9 to try does not work.

**Comment by SexuallyAbusive** [comment]
fixed everything with this guy on discord
