### ISSUE TITLE
Error during loading

### ISSUE THREAD

**Issue by nootkroot** [SexuallyAbusive/Zyklon#52]
This image pops up when I press the load button after opening the injector
![image](https://user-images.githubusercontent.com/65555981/103501124-25711080-4e02-11eb-88f7-12bf81ca60b9.png)

**Comment by nootkroot** [comment]
Fixed. Seems like it's because I was using mods like Optifine and Patcher. If you could create support for those mods that would be great.

**Comment by 3Q6Dev** [comment]
I haven't had any issues when using OptiFine, but when using Patcher, it injects and then displays the nametags hud etc, but then  the modules don't work. (at least autoclicker, for me)
